spring:
  application:
    name: spring-cloud-bus
  config:
    # optional keyword means the application will still start even if the config server is unavailable.
    import: optional:configserver:http://localhost:8888 #
  cloud:
    config:
      enabled:  # broadcasting state changes
      uri: http://localhost:8888
    bus:
      enabled: true
      refresh:
        enabled: true # Enables the /bus/refresh endpoint to refresh configurations
      trace:
        enabled: true # Enables tracing for the bus events
      env:
        enabled: true # Enables the /bus/env endpoint to update environment properties
  rabbitmq: # RabbitMQ Configuration
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*" # expose all routs
logging:
  level:
    org.springframework.cloud: DEBUG
